### ISSUE TITLE
a hint for version numbers in the docs

### ISSUE THREAD

**Issue by b1r63r** [robertdebock/ansible-role-docker_compose#3]
## Proposed feature

Add a hint that version 2.* version numbers of docker-compose contain a v as first letter while version 1.* does not. The docker_compose_version variable must reflect this

## Rationale

I lost 10-15 minutes myself staring at the version page and wondering why I couldn't get it to install version 2.*

## Additional context

Add any other context about the feature request here.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
Good one. I've just pushed a change, not including the `v`, so likely to fail. I'll address it when it causes issues.
